const oils = [
    { 
        name: "Basil",
        desc: "This crisp smelling essential oil awakens the mind to clarity of thought, steadies the nerves, while easing sinus congestion, cooling down fevers and treating menstrual problems.",
        url: './img/oil-img/basil.jpg',
        mood: "awaken",
        level: "top",
        pregnant: null,
        allergies: null,
        kid: null,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    { 
        name: "Bergamot",
        desc: "This fresh smelling essential oil is great for creating a more relaxed and happy feeling, relieving urinary tract infections, boosting the liver, spleen and stomach, while fighting oily skin and cold sores.",
        url: './img/oil-img/bergamot.jpg',
        mood: "calm",
        level: "top",
        pregnant: null,
        allergies: null,
        kid: null,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    { 
        name: "Cajuput",
        desc: "This powerful oil is used with great success for digestive and skin problems and helps to balance the mind by clearing thoughts, stimulating the mind and dispelling the feeling of sluggishness.",
        url: './img/oil-img/cajuput.jpg',
        mood: "awaken",
        level: "top",
        pregnant: null,
        allergies: null,
        kid: null,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    { 
        name: "Cinnamon",
        desc: "This spicy essential oil fights exhaustion and a feeling of depression and weakness. It has powerful anti-rheumatic properties, is useful in the digestive system, while fighting colds and flu as well.",
        url: './img/oil-img/cinnamon.jpg',
        mood: "sensual",
        level: "top",
        pregnant: null,
        allergies: null,
        kid: null,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    { 
        name: 'Clary Sage',
        desc: 'This sweet, somewhat herbaceous oil has great benefits - not only for easing depression and nervous burn-out, but for a host of female complaints and for relieving congested complexions.',
        url: './img/oil-img/clary-sage.jpg',
        mood: 'calm',
        level: "top",
        pregnant: null,
        allergies: null,
        kid: null,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    { 
        name: 'Coriander',
        desc: 'The warm, spicy essential oil helps to ease the mind and fight fatigue, while it warms and calms the digestive system, relieves rheumatism and arthritic pain, muscular spasms and detoxifies the body.',
        url: './img/oil-img/coriander.jpg',
        mood: 'calm',
        level: "top",
        pregnant: null,
        allergies: null,
        kid: null,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    { 
        name: 'Eucalyptus',
        desc: 'This clear, sharp essential oil helps to clear the mind and focus concentration. It is very valuable in fighting respiratory problems, inflammation and sore muscles, headaches and nervous exhaustion.',
        url: './img/oil-img/eucalyptus.jpg',
        mood: 'calm',
        level: "top",
        pregnant: null,
        allergies: null,
        kid: null,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    { 
        name: 'Grapefruit',
        desc: 'This sharp essential oil is useful for more than just fighting cellulite and boosting your lymphatic system - it positively affects your mood and revives the mind while stimulating the digestive system and clearing up acne.',
        url: './img/oil-img/grapefruit.jpg',
        mood: 'awaken',
        level: "top",
        pregnant: null,
        allergies: null,
        kid: null,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    { 
        name: 'Lemon',
        desc: 'This clean smelling citrus essential oil is not only good for helping you make decisions and to improve your concentration. It also cuts down on acidity in the body, assisting with digestion, arthritis, and acne.',
        url: './img/oil-img/lemon.jpg',
        mood: 'awaken',
        level: "top",
        pregnant: null,
        allergies: null,
        kid: null,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    { 
        name: 'Lemongrass',
        desc: 'This sweet, fresh smelling oil can be used with success for fighting jet lag, cellulite, revitalizing a tired body and mind, as well as keeping the family pet free of fleas and ticks.',
        url: './img/oil-img/lemongrass.jpg',
        mood: 'awaken',
        level: "top",
        pregnant: null,
        allergies: null,
        kid: null,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    { 
        name: 'Lime',
        desc: 'This sharp, clear smelling citrus oil can help lift depression and lighten your mood when feeling blue. It is used to fight cellulite and to tone the skin in general.',
        url: './img/oil-img/lime.jpg',
        mood: 'awaken',
        level: "top",
        pregnant: null,
        allergies: null,
        kid: null,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    // { 
    //     name: 'Mandarin',
    //     desc: null,
    //     mood: null,
    //     level: "top",
    //     pregnant: null,
    //     allergies: null,
    //     kid: null,
    // },
    { 
        name: 'Neroli',
        desc: 'This sweet, floral essential oil has a greatly relaxing effect on the body and mind, relieving muscle spasms, calming heart palpitations and has a wonderful regenerative effect on the skin.',
        url: './img/oil-img/neroli.jpg',
        mood: 'sensual',
        level: "top",
        pregnant: null,
        allergies: null,
        kid: null,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    { 
        name: 'Orange',
        desc: 'This unpretentious, citrusy essential oil is used to create the feeling of happiness and warmth, while calming nervous digestive problems. It deals well with colds and flu while eliminating toxins.',
        url: './img/oil-img/orange.jpg',
        mood: 'calm',
        level: "top",
        pregnant: null,
        allergies: null,
        kid: null,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    { 
        name: 'Peppermint',
        desc: 'This cooling and refreshing essential oil is used in aromatherapy to stimulate the mind, increase mental agility and to increase focus. It also cools the skin, reducing redness and calming irritation.',
        url: './img/oil-img/peppermint.jpg',
        mood: 'awaken',
        level: "top",
        pregnant: null,
        allergies: null,
        kid: null,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    { 
        name: 'Petitgrain',
        desc: 'This crisp and clear essential oil is most useful to boost the conscious intellectual side of your mind, while calming anger and panic. Its relaxing properties help insomnia while fighting skin blemishes.',
        url: './img/oil-img/petitgrain.jpg',
        mood: 'calm',
        level: "top",
        pregnant: null,
        allergies: null,
        kid: null,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    { 
        name: 'Sage',
        desc: 'This sharp, herbal essential oil is great for relieving grief and quickening the senses, while stimulating the lymphatic system and helping with female problems, such as sterility and menopausal problems.',
        url: './img/oil-img/sage.jpg',
        mood: 'awaken',
        level: "top",
        pregnant: null,
        allergies: null,
        kid: null,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    { 
        name: 'Spearmint',
        desc: 'This crisp, fresh essential oil has great benefits on the digestive system as well as assists the respiratory tract to relieve cough, asthma, and sinus. On the skin it calms itching and has a stimulant action on the mind.',
        url: './img/oil-img/spearmint.jpg',
        mood: 'awaken',
        level: "top",
        pregnant: null,
        allergies: null,
        kid: null,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    { 
        name: 'Tangerine',
        desc: 'This tangy and zesty essential oil has some great properties to help relieve stress and digestive problems, but is mostly used to increase circulation to the skin, reducing fluid retention and to help prevent stretch marks.',
        url: './img/oil-img/tangerine.jpg',
        mood: 'calm',
        level: "top",
        pregnant: null,
        allergies: null,
        kid: null,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    { 
        name: 'Tea Tree',
        desc: 'This medicinal-smelling essential oil is one of the most powerful immune system stimulants and sorts out most viral, bacterial and fungal infections in a snap, while it is great to clean wounds and also relieves muscle aches and pains.',
        url: './img/oil-img/tea-tree.jpg',
        mood: 'awaken',
        level: "top",
        pregnant: null,
        allergies: null,
        kid: null,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    { 
        name: 'Thyme',
        desc: 'This sweet yet strongly herbal essential oil can cause skin irritation, yet has great value to help with concentration and to focus. It is also an excellent lung stimulant and also has warming qualities that are great for arthritis and gout.',
        url: './img/oil-img/thyme.jpg',
        mood: 'awaken',
        level: "top",
        pregnant: null,
        allergies: null,
        kid: null,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    { 
        name: 'Lemon Verbena',
        desc: 'This sweet, fresh essential oil is great to banish blues and depression while boosting liver function and helping the digestive and respiratory system and at the same time softening the skin and reducing puffiness.',
        url: './img/oil-img/lemon-verbena.jpg',
        mood: 'awaken',
        level: "top",
        pregnant: null,
        allergies: null,
        kid: null,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    { 
        name: 'Bay',
        desc: 'This warming essential oil is a good antiseptic for the respiratory system, perks up the digestive system, settles stomach pain and expels wind. It also helps to promote confidence, courage and insight. Topically, it is most often used to combat hair loss.',
        url: './img/oil-img/bay.jpg',
        mood: 'calm',
        level: "middle",
        pregnant: null,
        allergies: null,
        kid: null,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    { 
        name: 'Black Pepper',
        desc: 'This warm and spicy essential oil helps to increase warmth of the body and mind, relieving sore muscles and joints, boost the immune and digestive system, stimulate the kidneys and disperse bruising by increasing circulation to the skin.',
        url: './img/oil-img/black-pepper.jpg',
        mood: 'awaken',
        level: "middle",
        pregnant: null,
        allergies: null,
        kid: null,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    { 
        name: 'Cardamom',
        desc: 'This sweet, spicy essential oil stimulates the mind into clarity, yet is subtly sexual in nature, awaking and enlivening the sensual side of a person. Its distinct scent can promote a positive mood and a sense of openness and mental clarity.',
        url: './img/oil-img/cardamom.jpg',
        mood: 'sensual',
        level: "middle",
        pregnant: null,
        allergies: null,
        kid: null,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    { 
        name: 'Cypress',
        desc: 'This clear and fresh smelling essential oil is a great boon to use during times of major upheavals and changes in your life, as it restores calm, sooths anger and making your life flow better. It has a positive effect on excess fluids in general.',
        url: './img/oil-img/cypress.jpg',
        mood: 'awaken',
        level: "middle",
        pregnant: null,
        allergies: null,
        kid: null,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    { 
        name: 'Fennel',
        desc: 'This herby essential oil is used in aromatherapy to boost your courage, resolve and strength in the face of adversity, while helping a huge array of digestive problems, fighting obesity, clearing an oily skin and fighting wrinkles.',
        url: './img/oil-img/fennel.jpg',
        mood: 'awaken',
        level: "middle",
        pregnant: null,
        allergies: null,
        kid: null,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    { 
        name: 'Geranium',
        desc: 'This fresh essential oil helps to balance the mind and emotions, while stimulating the adrenal cortex and balancing the hormonal system. It also  balances the production of sebum in the skin, while keeping it supple and helping with the healing of wounds.',
        url: './img/oil-img/geranium.jpg',
        mood: 'awaken',
        level: "middle",
        pregnant: null,
        allergies: null,
        kid: null,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    { 
        name: 'Hyssop',
        desc: 'This sweet, warm essential oil is effective in helping to treat female disorders and to relieve monthly water retention. It also helps the respiratory system get rid of mucus and bronchial spasms. It can be used to help wounds heal and dispersing bruises on the skin.',
        url: './img/oil-img/hyssop.jpg',
        mood: 'calm',
        level: "middle",
        pregnant: null,
        allergies: null,
        kid: null,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    { 
        name: 'Juniper',
        desc: 'This crisp essential oil is used to help stimulate and strengthen the nerves and bolster the spirits in challenging situations. It also is used to treat rheumatism, arthritis and gout, cellulite, acne, dermatitis, and blocked pores.',
        url: './img/oil-img/juniper.jpg',
        mood: 'awaken',
        level: "middle",
        pregnant: null,
        allergies: null,
        kid: null,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    { 
        name: 'Lavender',
        desc: 'This calming, relaxing essential oil, which combats stress and crisis, also has antiseptic properties that helps with cold and flu. It is excellent for asthma and migraines and supports female health. On the skin it also prevents scarring and balances the skin.',
        url: './img/oil-img/lavender.jpg',
        mood: 'calm',
        level: "middle",
        pregnant: null,
        allergies: null,
        kid: null,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    { 
        name: 'Marjoram',
        desc: 'This warm, slightly-spicy essential oil has value when used for asthma and other respiratory complaints and has a calming action on emotions. It helps hyperactive people calm down while boosting circulation.',
        url: './img/oil-img/marjoram.jpg',
        mood: 'calm',
        level: "middle",
        pregnant: null,
        allergies: null,
        kid: null,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    { 
        name: 'Melissa',
        desc: 'This sweet, citrus-like essential oil has a couple of uses in aromatherapy and helps to bring calmness to the mind, while having a great sedating effect, calming the heartbeat and palpitations.',
        url: './img/oil-img/melissa.jpg',
        mood: 'calm',
        level: "middle",
        pregnant: null,
        allergies: null,
        kid: null,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    { 
        name: 'Nutmeg',
        desc: 'This warming, spicy essential oil is used in aromatherapy to fight inflammations and muscle as well as rheumatic pain, while assisting the digestive system and supporting the reproductive system, and at the same time stimulating and invigorating the mind.',
        url: './img/oil-img/nutmeg.jpg',
        mood: 'sensual',
        level: "middle",
        pregnant: null,
        allergies: null,
        kid: null,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    { 
        name: 'Palma Rosa',
        desc: 'This sweet, floral essential oil has excellent skin care properties and is also used to relieve stiff and sore muscles, while calming the mind and uplifting and invigorating the spirits and clearing muddled thinking.',
        url: './img/oil-img/palmaRosa.jpg',
        mood: 'awaken',
        level: "middle",
        pregnant: null,
        allergies: null,
        kid: null,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    { 
        name: 'Pine',
        desc: 'Although this forest-smelling essential oil can cause allergic reactions, it is very useful to relieve mental, physical and sexual fatigue, while having a cleansing and clearing effect on a room.',
        url: './img/oil-img/pine.jpg',
        mood: 'awaken',
        level: "middle",
        pregnant: null,
        allergies: null,
        kid: null,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    { 
        name: 'Rosemary',
        desc: 'This crisp and clean smelling essential oil is great for stimulating the brain, improving memory and mental clarity. It also helps with stiff muscles and coldness as well as boosting the liver and gall bladder.',
        url: './img/oil-img/rosemary.jpg',
        mood: 'awaken',
        level: "middle",
        pregnant: null,
        allergies: null,
        kid: null,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    { 
        name: 'Spikenard',
        desc: 'This warm, misty essential oil can be effective for tension, stress, migraine, nervous indigestion and insomnia. It can help with rejuvenating mature skin, allergies, skin inflammations and rashes.',
        url: './img/oil-img/spikenard.jpg',
        mood: 'calm',
        level: "middle",
        pregnant: null,
        allergies: null,
        kid: null,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    { 
        name: 'Yarrow',
        desc: 'This sweet, spicy essential oil can be beneficial to the nervous, genito-urinary and digestive systems, and can assist with skin care.',
        url: './img/oil-img/yarrow.jpg',
        mood: 'awaken',
        level: "middle",
        pregnant: null,
        allergies: null,
        kid: null,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    { 
        name: 'Cassia',
        desc: 'This warm, exotic essential oil is more than just a fragrant oil, as it can be used in fever, chills and for supporting the digestive system.',
        url: './img/oil-img/cassia.jpg',
        mood: 'calm',
        level: "base",
        pregnant: null,
        allergies: null,
        kid: null,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    { 
        name: 'Cedarwood',
        desc: 'This clean smelling, balsamic essential oil does not only help calm and balance energy, but also promotes spirituality. It also helps to improve oily skin and clears up dandruff.',
        url: './img/oil-img/cedarwood.jpg',
        mood: 'calm',
        level: "base",
        pregnant: null,
        allergies: null,
        kid: null,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    { 
        name: 'Clove',
        desc: 'Although this warm, spicy essential oil has many wonderful properties - from stimulating the mind and lifting depression, to aiding digestion, relieving pain in arthritis and rheumatism, easing respiratory problems and assisting leg ulcers.',
        url: './img/oil-img/clove.jpg',
        mood: 'awaken',
        level: "base",
        pregnant: null,
        allergies: null,
        kid: null,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    { 
        name: 'Frankincense',
        desc: 'This woody, spicy essential oil has a wonderfully calming effect on the mind and helps to create inner peace. It also helps to sooth the respiratory and urinary tract and relieve pain associated with rheumatism and muscular aches',
        url: './img/oil-img/frankincense.jpg',
        mood: 'calm',
        level: "base",
        pregnant: null,
        allergies: null,
        kid: null,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    { 
        name: 'Ginger',
        desc: 'This spicy, warming essential oil is often used for digestive problems, as well as nausea - be that morning sickness or travel upset. It is also helps to treat colds and flu. It can also be used on the skin to help clear bruises.',
        url: './img/oil-img/ginger.jpg',
        mood: 'awaken',
        level: "base",
        pregnant: null,
        allergies: null,
        kid: null,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    { 
        name: 'Jasmine',
        desc: 'This sweet, exotic, and richly floral essential oil does more than just smell exquisite - it deeply relaxes, lifts depression and boosts confidence, eases childbirth, helps with sexual problems, sooths coughing and helps to reduce stretch marks and scars.',
        url: './img/oil-img/jasmine.jpg',
        mood: 'sensual',
        level: "base",
        pregnant: null,
        allergies: null,
        kid: null,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    { 
        name: 'Myrrh',
        desc: 'This warm, slightly-musty oil not only works on increasing your spiritual self, but produce wonderful results when used to treat female complaints, skin ailments, as well as detoxifying the body and expelling mucus from the body.',
        url: './img/oil-img/myrrh.jpg',
        mood: 'awaken',
        level: "base",
        pregnant: null,
        allergies: null,
        kid: null,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    { 
        name: 'Patchouli',
        desc: 'This rich, musky-sweet essential oil is great for fighting depression and anxiety. It has great diuretic properties and also helps break down cellulite, while stimulating the regeneration of skin cells, speeding up healing and preventing ugly scars forming when wounds heal.',
        url: './img/oil-img/patchouli.jpg',
        mood: 'calm',
        level: "base",
        pregnant: null,
        allergies: null,
        kid: null,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    { 
        name: 'Rose',
        desc: 'This deep, fresh aroma essential oil is useful for lifting depression, fighting frigidity and impotence and for skin rejuvenation. It has excellent cell stimulant and tissue regeneration properties, making it a valuable ingredient in mature skin care.',
        url: './img/oil-img/rose.jpg',
        mood: 'awaken',
        level: "base",
        pregnant: null,
        allergies: null,
        kid: null,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    { 
        name: 'Rosewood',
        desc: 'This slightly spicy, floral essential oil is useful for lifting depression, fighting frigidity and impotence and for skin rejuvenation. It has excellent cell stimulant and tissue regeneration properties, making it a valuable ingredient in mature skin care.',
        url: './img/oil-img/rosewood.jpg',
        mood: 'awaken',
        level: "base",
        pregnant: null,
        allergies: null,
        kid: null,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    { 
        name: 'Sandalwood',
        desc: 'This woody, exotic essential oil has wonderful qualities for relieving both chest and urinary tract infections, while assisting the skin in promoting hydration and moisture and for the mind it creates a calming and harmonizing effect, while reducing tension and confusion.',
        url: './img/oil-img/sandalwood.jpg',
        mood: 'sensual',
        level: "base",
        pregnant: null,
        allergies: null,
        kid: null,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    { 
        name: 'Vanilla',
        desc: 'This aromatic essential oil has strong effects on the mind and body and is used to fight inflammation, works as an antidepressant, contains high levels of antioxidants, promotes skin and hair health, relieves muscle pain and cramps, and balances hormones naturally.',
        url: './img/oil-img/vanilla.jpg',
        mood: 'sensual',
        level: "base",
        pregnant: null,
        allergies: null,
        kid: null,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    { 
        name: 'Vetiver',
        desc: 'This earthy essential oil has a wonderful effect on the mind and body and is useful to dispel irritability while having a balancing effect on the hormonal system. It is also used to reduce wrinkles and stretch marks while moisturizing the skin and helping wounds heal.',
        url: './img/oil-img/vetiver.jpg',
        mood: 'calm',
        level: "base",
        pregnant: null,
        allergies: null,
        kid: null,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    { 
        name: 'Ylang Ylang',
        desc: 'This extremely fragrant essential oil has a calming effect on the mind and body and is used in cases of frigidity and impotence. It has a wonderfully balancing and stimulating effect on the skin, to correct sebum production and is also used to stimulate hair growth.',
        url: './img/oil-img/ylangYlang.jpg',
        mood: 'sensual',
        level: "base",
        pregnant: null,
        allergies: null,
        kid: null,
        createdAt: new Date(),
        updatedAt: new Date()
    }
]

module.exports = oils;